spring:
  application:
    name: API_Clinica

  datasource:
    url: jdbc:mysql://localhost:3306/api_clinica?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}